#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-http-github-secret
  annotations:
    tekton.dev/git-0: #@ data.values.imported.github.httphost 
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.imported.github.username
  password: #@ data.values.imported.github.token