#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-gitlab-secret
  annotations:
    tekton.dev/git-0: #@ data.values.imported.gitlab.sshhost 
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: #@ data.values.imported.gitlab.sshprivatekey
  known_hosts: #@ data.values.imported.gitlab.knownhosts
  identity: #@ data.values.imported.gitlab.identity
  identity.pub: #@ data.values.imported.gitlab.identitypub