#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-http-gitlab-secret
  annotations:
    tekton.dev/git-0: #@ data.values.imported.gitlab.httpshost
    tekton.dev/git-1: #@ data.values.imported.gitlab.httphost 
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.imported.gitlab.username
  password: #@ data.values.imported.gitlab.token
  caFile: #@ data.values.imported.gitlab.caFile
