#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-github-secret
  annotations:
    tekton.dev/git-0: #@ data.values.imported.github.sshhost 
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: #@ data.values.imported.github.sshprivatekey
  known_hosts: #@ data.values.imported.github.knownhosts
  identity: #@ data.values.imported.github.identity
  identity.pub: #@ data.values.imported.github.identitypub