#@ load("@ytt:data", "data")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#! This if condition ensures that this Golang Tekton pipeline is only created if the supply chain is testing or testing_scanning, and the TAP profile used is full, iterate or build.
#@ if/end in_list('supply_chain', ['basic', 'testing', 'testing_scanning']) and in_list('profile', ['full', 'iterate', 'build']):
---
apiVersion: v1
kind: Secret
metadata:
 name: settings-xml
type: service.binding/maven
stringData:
  type: maven
  provider: sample
  settings.xml: |
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">

        <mirrors>
          <mirror>
            <id> maven-default-http-blocker</id>
            <mirrorOf>external:http:*,!central,!snapshots</mirrorOf>
            <name>Pseudo repository to mirror external repositories initally using HTTP.</name>
            <url>http://0.0.0.0/</url>
            <blocked>true</blocked>
          </mirror>

          <mirror>
            <id>artifactory-releases</id>
            <name>Artifactory-releases</name>
            <url>http://10.220.80.28:8082/artifactory/my-maven-virtual-releases/</url>
            <mirrorOf>*,!snapshots</mirrorOf>
          </mirror>
          
          <mirror>
            <id>artifactory-snapshots</id>
            <name>Artifactory-snapshots</name>
            <url>http://10.220.80.28:8082/artifactory/my-maven-virtual-snapshots/</url>
            <mirrorOf>snapshots</mirrorOf>
          </mirror>
        </mirrors>        

        <profiles>
          <profile>
            <id>artifactory</id>

              <repositories>
                  <repository>
                      <id>central</id>
                      <url>http://10.220.80.28:8082/artifactory/my-maven-virtual-releases/</url>
                      <snapshots>
                          <enabled>false</enabled>
                      </snapshots>
                  </repository>
                  <repository>
                      <id>snapshots</id>
                      <url>http://10.220.80.28:8082/artifactory/my-maven-virtual-snapshots/</url>
                      <releases>
                          <enabled>false</enabled>
                      </releases>
                  </repository>
              </repositories>
              <pluginRepositories>
                  <pluginRepository>
                      <id>central</id>
                      <url>http://10.220.80.28:8082/artifactory/my-maven-virtual-releases</url>
                      <snapshots>
                          <enabled>false</enabled>
                      </snapshots>
                  </pluginRepository>
                  <pluginRepository>
                      <id>snapshots</id>
                      <url>http://10.220.80.28:8082/artifactory/my-maven-virtual-snapshots</url>
                      <releases>
                          <enabled>false</enabled>
                      </releases>
                  </pluginRepository>
              </pluginRepositories>

          </profile>
        </profiles>

        <activeProfiles>
          <activeProfile>artifactory</activeProfile>
        </activeProfiles>

    </settings>
